### ISSUE TITLE
DLC file lists and links

### ISSUE THREAD

**Issue by Darthagnon** [GrenderG/goshawk#2]
I went through quite a bit of effort a few years ago to get all the DLC for the EU releases of the 3DS Monster Hunter games. Maybe you already have the data, but just in case its useful, here are some links to Google Drive and relevant Reddit threads:

- https://old.reddit.com/r/CitraPiracy/comments/kmrmxd/anyone_have_monster_hunter_3_ultimate_dlc/
- Base64:`aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xazl0NGx1SmxJdUM5QXdfamNzai1HM2owRUdfY3U1WE4vdmlldz91c3A9ZHJpdmVfbGluaw==` (I don't own the copyright, so will remove on request)
- https://old.reddit.com/r/mh4u/comments/1d1cgpt/compilation_of_dlc_for_mh4u_mh4g_mhxx_3ds_only/

**Comment by GrenderG** [comment]
Thank you! We already have those files, we are just missing some things that were time limited like some USJ collabs.
